{"created": 1754129127.5355165, "duration": 0.9401097297668457, "exitcode": 2, "root": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem", "environment": {}, "summary": {"total": 0, "collected": 143}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "tests/__init__.py", "type": "Package"}, {"nodeid": "tests/api/__init__.py", "type": "Package"}, {"nodeid": "tests/api/incidents/test_incidents_crud.py", "type": "Module"}, {"nodeid": "tests/api/incidents/test_incidents_history.py", "type": "Module"}, {"nodeid": "tests/automation/test_report_generator.py", "type": "Module"}, {"nodeid": "tests/e2e/__init__.py", "type": "Package"}, {"nodeid": "tests/e2e/pages/__init__.py", "type": "Package"}, {"nodeid": "tests/e2e/scenarios/test_incident_workflow.py", "type": "Module"}, {"nodeid": "tests/load/test_api_load.py", "type": "Module"}, {"nodeid": "tests/load/test_api_performance.py", "type": "Module"}, {"nodeid": "tests/load/test_comprehensive_load.py", "type": "Module"}, {"nodeid": "tests/load/test_simple_load.py", "type": "Module"}, {"nodeid": "tests/utils/test_health_check.py", "type": "Module"}, {"nodeid": "tests/utils/test_runner.py", "type": "Module"}, {"nodeid": "tests/utils/test_suite_final_repair_engine.py", "type": "Module"}, {"nodeid": "tests/utils/test_suite_infinite_loop_repair_engine.py", "type": "Module"}]}, {"nodeid": "tests/test_ci_e2e_integration.py::TestCIE2EIntegration", "outcome": "passed", "result": [{"nodeid": "tests/test_ci_e2e_integration.py::TestCIE2EIntegration::test_workflow_trigger_simulation", "type": "Function", "lineno": 33}, {"nodeid": "tests/test_ci_e2e_integration.py::TestCIE2EIntegration::test_auto_repair_cycle_performance", "type": "Function", "lineno": 54}, {"nodeid": "tests/test_ci_e2e_integration.py::TestCIE2EIntegration::test_error_detection_and_logging", "type": "Function", "lineno": 85}, {"nodeid": "tests/test_ci_e2e_integration.py::TestCIE2EIntegration::test_ci_retry_log_creation", "type": "Function", "lineno": 114}, {"nodeid": "tests/test_ci_e2e_integration.py::TestCIE2EIntegration::test_notification_system_integration", "type": "Function", "lineno": 147}, {"nodeid": "tests/test_ci_e2e_integration.py::TestCIE2EIntegration::test_performance_metrics_collection", "type": "Function", "lineno": 168}, {"nodeid": "tests/test_ci_e2e_integration.py::TestCIE2EIntegration::test_system_health_check", "type": "Function", "lineno": 209}]}, {"nodeid": "tests/test_ci_e2e_integration.py", "outcome": "passed", "result": [{"nodeid": "tests/test_ci_e2e_integration.py::TestCIE2EIntegration", "type": "Class"}]}, {"nodeid": "tests/test_ci_workflow_validation.py::TestCIWorkflowValidation", "outcome": "passed", "result": [{"nodeid": "tests/test_ci_workflow_validation.py::TestCIWorkflowValidation::test_workflow_files_exist", "type": "Function", "lineno": 40}, {"nodeid": "tests/test_ci_workflow_validation.py::TestCIWorkflowValidation::test_yaml_syntax_validation", "type": "Function", "lineno": 46}, {"nodeid": "tests/test_ci_workflow_validation.py::TestCIWorkflowValidation::test_github_actions_schema_compliance", "type": "Function", "lineno": 57}, {"nodeid": "tests/test_ci_workflow_validation.py::TestCIWorkflowValidation::test_dependency_workflow_validation", "type": "Function", "lineno": 81}, {"nodeid": "tests/test_ci_workflow_validation.py::TestCIWorkflowValidation::test_error_handling_configuration", "type": "Function", "lineno": 102}, {"nodeid": "tests/test_ci_workflow_validation.py::TestCIWorkflowValidation::test_retry_logic_validation", "type": "Function", "lineno": 117}, {"nodeid": "tests/test_ci_workflow_validation.py::TestCIWorkflowValidation::test_log_output_configuration", "type": "Function", "lineno": 144}, {"nodeid": "tests/test_ci_workflow_validation.py::TestCIWorkflowValidation::test_notification_integration", "type": "Function", "lineno": 161}, {"nodeid": "tests/test_ci_workflow_validation.py::TestCIWorkflowValidation::test_infinite_loop_repair_integration", "type": "Function", "lineno": 178}, {"nodeid": "tests/test_ci_workflow_validation.py::TestCIWorkflowValidation::test_itsm_compliance_requirements", "type": "Function", "lineno": 204}, {"nodeid": "tests/test_ci_workflow_validation.py::TestCIWorkflowValidation::test_performance_metrics", "type": "Function", "lineno": 222}]}, {"nodeid": "tests/test_ci_workflow_validation.py", "outcome": "passed", "result": [{"nodeid": "tests/test_ci_workflow_validation.py::TestCIWorkflowValidation", "type": "Class"}]}, {"nodeid": "tests/test_loop_repair_engine.py", "outcome": "failed", "result": [], "longrepr": "ImportError while importing test module '/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/test_loop_repair_engine.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.12/importlib/__init__.py:90: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/test_loop_repair_engine.py:22: in <module>\n    import aiohttp\nE   ModuleNotFoundError: No module named 'aiohttp'"}, {"nodeid": "tests/test_playwright_e2e.py", "outcome": "failed", "result": [], "longrepr": "ImportError while importing test module '/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/test_playwright_e2e.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.12/importlib/__init__.py:90: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/test_playwright_e2e.py:19: in <module>\n    import aiohttp\nE   ModuleNotFoundError: No module named 'aiohttp'"}, {"nodeid": "tests/test_suite_final_repair.py::TestSuiteFinalRepair", "outcome": "passed", "result": [{"nodeid": "tests/test_suite_final_repair.py::TestSuiteFinalRepair::test_basic_api_connectivity", "type": "Function", "lineno": 34}, {"nodeid": "tests/test_suite_final_repair.py::TestSuiteFinalRepair::test_health_check_endpoint_mock", "type": "Function", "lineno": 51}, {"nodeid": "tests/test_suite_final_repair.py::TestSuiteFinalRepair::test_concurrent_requests_simulation", "type": "Function", "lineno": 78}, {"nodeid": "tests/test_suite_final_repair.py::TestSuiteFinalRepair::test_database_connectivity_mock", "type": "Function", "lineno": 103}, {"nodeid": "tests/test_suite_final_repair.py::TestSuiteFinalRepair::test_authentication_system_mock", "type": "Function", "lineno": 126}, {"nodeid": "tests/test_suite_final_repair.py::TestSuiteFinalRepair::test_incident_management_workflow", "type": "Function", "lineno": 157}, {"nodeid": "tests/test_suite_final_repair.py::TestSuiteFinalRepair::test_end_to_end_user_journey", "type": "Function", "lineno": 195}, {"nodeid": "tests/test_suite_final_repair.py::TestSuiteFinalRepair::test_system_load_handling", "type": "Function", "lineno": 221}, {"nodeid": "tests/test_suite_final_repair.py::TestSuiteFinalRepair::test_security_measures", "type": "Function", "lineno": 258}, {"nodeid": "tests/test_suite_final_repair.py::TestSuiteFinalRepair::test_final_system_health_validation", "type": "Function", "lineno": 284}]}, {"nodeid": "tests/test_suite_final_repair.py::TestSuiteRealTimeMonitoring", "outcome": "passed", "result": [{"nodeid": "tests/test_suite_final_repair.py::TestSuiteRealTimeMonitoring::test_5_second_interval_monitoring", "type": "Function", "lineno": 328}, {"nodeid": "tests/test_suite_final_repair.py::TestSuiteRealTimeMonitoring::test_10_cycle_automation_loop", "type": "Function", "lineno": 367}]}, {"nodeid": "tests/test_suite_final_repair.py::TestSuiteCompletionValidation", "outcome": "passed", "result": [{"nodeid": "tests/test_suite_final_repair.py::TestSuiteCompletionValidation::test_github_actions_workflow_simulation", "type": "Function", "lineno": 404}, {"nodeid": "tests/test_suite_final_repair.py::TestSuiteCompletionValidation::test_final_health_status_achievement", "type": "Function", "lineno": 429}]}, {"nodeid": "tests/test_suite_final_repair.py", "outcome": "passed", "result": [{"nodeid": "tests/test_suite_final_repair.py::TestSuiteFinalRepair", "type": "Class"}, {"nodeid": "tests/test_suite_final_repair.py::TestSuiteRealTimeMonitoring", "type": "Class"}, {"nodeid": "tests/test_suite_final_repair.py::TestSuiteCompletionValidation", "type": "Class"}]}, {"nodeid": "tests/__init__.py", "outcome": "passed", "result": [{"nodeid": "tests/test_ci_e2e_integration.py", "type": "Module"}, {"nodeid": "tests/test_ci_workflow_validation.py", "type": "Module"}, {"nodeid": "tests/test_loop_repair_engine.py", "type": "Module"}, {"nodeid": "tests/test_playwright_e2e.py", "type": "Module"}, {"nodeid": "tests/test_suite_final_repair.py", "type": "Module"}]}, {"nodeid": "tests/api/test_auth.py::TestAuthentication", "outcome": "passed", "result": [{"nodeid": "tests/api/test_auth.py::TestAuthentication::test_oauth_token_request_success", "type": "Function", "lineno": 14}, {"nodeid": "tests/api/test_auth.py::TestAuthentication::test_oauth_token_request_invalid_client", "type": "Function", "lineno": 49}, {"nodeid": "tests/api/test_auth.py::TestAuthentication::test_oauth_token_request_invalid_grant", "type": "Function", "lineno": 78}, {"nodeid": "tests/api/test_auth.py::TestAuthentication::test_refresh_token_success", "type": "Function", "lineno": 107}, {"nodeid": "tests/api/test_auth.py::TestAuthentication::test_api_request_with_valid_token", "type": "Function", "lineno": 138}, {"nodeid": "tests/api/test_auth.py::TestAuthentication::test_api_request_with_invalid_token", "type": "Function", "lineno": 159}, {"nodeid": "tests/api/test_auth.py::TestAuthentication::test_api_request_without_token", "type": "Function", "lineno": 186}, {"nodeid": "tests/api/test_auth.py::TestAuthentication::test_token_expiration_handling", "type": "Function", "lineno": 205}, {"nodeid": "tests/api/test_auth.py::TestAuthentication::test_login_validation_comprehensive", "type": "Function", "lineno": 232}, {"nodeid": "tests/api/test_auth.py::TestAuthentication::test_session_management", "type": "Function", "lineno": 263}, {"nodeid": "tests/api/test_auth.py::TestAuthentication::test_multi_factor_authentication", "type": "Function", "lineno": 292}, {"nodeid": "tests/api/test_auth.py::TestAuthentication::test_concurrent_auth_requests", "type": "Function", "lineno": 346}, {"nodeid": "tests/api/test_auth.py::TestAuthentication::test_rate_limiting_with_authentication", "type": "Function", "lineno": 395}]}, {"nodeid": "tests/api/test_auth.py", "outcome": "passed", "result": [{"nodeid": "tests/api/test_auth.py::TestAuthentication", "type": "Class"}]}, {"nodeid": "tests/api/test_comprehensive_api.py::TestComprehensiveAPI", "outcome": "passed", "result": [{"nodeid": "tests/api/test_comprehensive_api.py::TestComprehensiveAPI::test_incident_full_lifecycle", "type": "Function", "lineno": 17}, {"nodeid": "tests/api/test_comprehensive_api.py::TestComprehensiveAPI::test_problem_management_api", "type": "Function", "lineno": 125}, {"nodeid": "tests/api/test_comprehensive_api.py::TestComprehensiveAPI::test_change_management_api", "type": "Function", "lineno": 152}, {"nodeid": "tests/api/test_comprehensive_api.py::TestComprehensiveAPI::test_cmdb_api_endpoints", "type": "Function", "lineno": 180}, {"nodeid": "tests/api/test_comprehensive_api.py::TestComprehensiveAPI::test_authentication_endpoints", "type": "Function", "lineno": 207}, {"nodeid": "tests/api/test_comprehensive_api.py::TestComprehensiveAPI::test_reporting_api_endpoints", "type": "Function", "lineno": 242}, {"nodeid": "tests/api/test_comprehensive_api.py::TestComprehensiveAPI::test_notification_api_endpoints", "type": "Function", "lineno": 287}, {"nodeid": "tests/api/test_comprehensive_api.py::TestComprehensiveAPI::test_user_management_api", "type": "Function", "lineno": 328}, {"nodeid": "tests/api/test_comprehensive_api.py::TestComprehensiveAPI::test_category_management_api", "type": "Function", "lineno": 369}, {"nodeid": "tests/api/test_comprehensive_api.py::TestComprehensiveAPI::test_team_management_api", "type": "Function", "lineno": 414}, {"nodeid": "tests/api/test_comprehensive_api.py::TestComprehensiveAPI::test_health_check_endpoints", "type": "Function", "lineno": 454}, {"nodeid": "tests/api/test_comprehensive_api.py::TestComprehensiveAPI::test_search_api_endpoints", "type": "Function", "lineno": 489}]}, {"nodeid": "tests/api/test_comprehensive_api.py::TestAPIPerformance", "outcome": "passed", "result": [{"nodeid": "tests/api/test_comprehensive_api.py::TestAPIPerformance::test_incident_creation_performance", "type": "Function", "lineno": 546}, {"nodeid": "tests/api/test_comprehensive_api.py::TestAPIPerformance::test_incident_list_performance", "type": "Function", "lineno": 572}, {"nodeid": "tests/api/test_comprehensive_api.py::TestAPIPerformance::test_concurrent_api_requests", "type": "Function", "lineno": 607}, {"nodeid": "tests/api/test_comprehensive_api.py::TestAPIPerformance::test_api_rate_limiting", "type": "Function", "lineno": 658}]}, {"nodeid": "tests/api/test_comprehensive_api.py::TestAPISecurity", "outcome": "passed", "result": [{"nodeid": "tests/api/test_comprehensive_api.py::TestAPISecurity::test_unauthorized_access", "type": "Function", "lineno": 707}, {"nodeid": "tests/api/test_comprehensive_api.py::TestAPISecurity::test_invalid_token_access", "type": "Function", "lineno": 729}, {"nodeid": "tests/api/test_comprehensive_api.py::TestAPISecurity::test_sql_injection_protection", "type": "Function", "lineno": 758}, {"nodeid": "tests/api/test_comprehensive_api.py::TestAPISecurity::test_xss_protection", "type": "Function", "lineno": 782}]}, {"nodeid": "tests/api/test_comprehensive_api.py", "outcome": "passed", "result": [{"nodeid": "tests/api/test_comprehensive_api.py::TestComprehensiveAPI", "type": "Class"}, {"nodeid": "tests/api/test_comprehensive_api.py::TestAPIPerformance", "type": "Class"}, {"nodeid": "tests/api/test_comprehensive_api.py::TestAPISecurity", "type": "Class"}]}, {"nodeid": "tests/api/test_health.py::TestHealthCheck", "outcome": "passed", "result": [{"nodeid": "tests/api/test_health.py::TestHealthCheck::test_health_endpoint_success", "type": "Function", "lineno": 11}, {"nodeid": "tests/api/test_health.py::TestHealthCheck::test_version_endpoint_success", "type": "Function", "lineno": 33}]}, {"nodeid": "tests/api/test_health.py::TestAPIPerformance", "outcome": "passed", "result": [{"nodeid": "tests/api/test_health.py::TestAPIPerformance::test_health_endpoint_performance", "type": "Function", "lineno": 61}, {"nodeid": "tests/api/test_health.py::TestAPIPerformance::test_concurrent_health_requests", "type": "Function", "lineno": 74}]}, {"nodeid": "tests/api/test_health.py", "outcome": "passed", "result": [{"nodeid": "tests/api/test_health.py::TestHealthCheck", "type": "Class"}, {"nodeid": "tests/api/test_health.py::TestAPIPerformance", "type": "Class"}]}, {"nodeid": "tests/api/__init__.py", "outcome": "passed", "result": [{"nodeid": "tests/api/test_auth.py", "type": "Module"}, {"nodeid": "tests/api/test_comprehensive_api.py", "type": "Module"}, {"nodeid": "tests/api/test_health.py", "type": "Module"}]}, {"nodeid": "tests/api/incidents/test_incidents_crud.py::TestIncidentsCRUD", "outcome": "passed", "result": [{"nodeid": "tests/api/incidents/test_incidents_crud.py::TestIncidentsCRUD::test_create_incident_success", "type": "Function", "lineno": 16}, {"nodeid": "tests/api/incidents/test_incidents_crud.py::TestIncidentsCRUD::test_create_incident_validation_error", "type": "Function", "lineno": 44}, {"nodeid": "tests/api/incidents/test_incidents_crud.py::TestIncidentsCRUD::test_get_incident_by_id_success", "type": "Function", "lineno": 90}, {"nodeid": "tests/api/incidents/test_incidents_crud.py::TestIncidentsCRUD::test_get_incident_not_found", "type": "Function", "lineno": 141}, {"nodeid": "tests/api/incidents/test_incidents_crud.py::TestIncidentsCRUD::test_update_incident_success", "type": "Function", "lineno": 165}, {"nodeid": "tests/api/incidents/test_incidents_crud.py::TestIncidentsCRUD::test_update_incident_invalid_status_transition", "type": "Function", "lineno": 196}, {"nodeid": "tests/api/incidents/test_incidents_crud.py::TestIncidentsCRUD::test_list_incidents_with_pagination", "type": "Function", "lineno": 231}, {"nodeid": "tests/api/incidents/test_incidents_crud.py::TestIncidentsCRUD::test_list_incidents_with_filters", "type": "Function", "lineno": 288}, {"nodeid": "tests/api/incidents/test_incidents_crud.py::TestIncidentsCRUD::test_delete_incident_success", "type": "Function", "lineno": 333}, {"nodeid": "tests/api/incidents/test_incidents_crud.py::TestIncidentsCRUD::test_delete_incident_not_found", "type": "Function", "lineno": 347}, {"nodeid": "tests/api/incidents/test_incidents_crud.py::TestIncidentsCRUD::test_bulk_incident_operations", "type": "Function", "lineno": 370}]}, {"nodeid": "tests/api/incidents/test_incidents_crud.py", "outcome": "passed", "result": [{"nodeid": "tests/api/incidents/test_incidents_crud.py::TestIncidentsCRUD", "type": "Class"}]}, {"nodeid": "tests/api/incidents/test_incidents_history.py::TestIncidentHistory", "outcome": "passed", "result": [{"nodeid": "tests/api/incidents/test_incidents_history.py::TestIncidentHistory::test_get_incident_history_success", "type": "Function", "lineno": 14}, {"nodeid": "tests/api/incidents/test_incidents_history.py::TestIncidentHistory::test_get_incident_history_with_filters", "type": "Function", "lineno": 95}, {"nodeid": "tests/api/incidents/test_incidents_history.py::TestIncidentHistory::test_add_work_note_success", "type": "Function", "lineno": 140}, {"nodeid": "tests/api/incidents/test_incidents_history.py::TestIncidentHistory::test_add_work_note_validation_error", "type": "Function", "lineno": 176}, {"nodeid": "tests/api/incidents/test_incidents_history.py::TestIncidentHistory::test_get_work_notes_list", "type": "Function", "lineno": 216}, {"nodeid": "tests/api/incidents/test_incidents_history.py::TestIncidentHistory::test_incident_assignment_workflow", "type": "Function", "lineno": 264}, {"nodeid": "tests/api/incidents/test_incidents_history.py::TestIncidentHistory::test_incident_escalation_workflow", "type": "Function", "lineno": 304}, {"nodeid": "tests/api/incidents/test_incidents_history.py::TestIncidentHistory::test_incident_resolution_workflow", "type": "Function", "lineno": 342}, {"nodeid": "tests/api/incidents/test_incidents_history.py::TestIncidentHistory::test_incident_closure_workflow", "type": "Function", "lineno": 387}]}, {"nodeid": "tests/api/incidents/test_incidents_history.py", "outcome": "passed", "result": [{"nodeid": "tests/api/incidents/test_incidents_history.py::TestIncidentHistory", "type": "Class"}]}, {"nodeid": "tests/automation/test_report_generator.py::TestReportGenerator", "outcome": "passed", "result": []}, {"nodeid": "tests/automation/test_report_generator.py", "outcome": "passed", "result": [{"nodeid": "tests/automation/test_report_generator.py::TestReportGenerator", "type": "Class"}]}, {"nodeid": "tests/e2e/test_basic_ui.py::TestBasicUI", "outcome": "passed", "result": [{"nodeid": "tests/e2e/test_basic_ui.py::TestBasicUI::test_homepage_loads", "type": "Function", "lineno": 11}, {"nodeid": "tests/e2e/test_basic_ui.py::TestBasicUI::test_navigation_menu", "type": "Function", "lineno": 29}, {"nodeid": "tests/e2e/test_basic_ui.py::TestBasicUI::test_incident_creation_form", "type": "Function", "lineno": 50}, {"nodeid": "tests/e2e/test_basic_ui.py::TestBasicUI::test_search_functionality", "type": "Function", "lineno": 77}, {"nodeid": "tests/e2e/test_basic_ui.py::TestBasicUI::test_responsive_design", "type": "Function", "lineno": 102}, {"nodeid": "tests/e2e/test_basic_ui.py::TestBasicUI::test_form_validation", "type": "Function", "lineno": 122}, {"nodeid": "tests/e2e/test_basic_ui.py::TestBasicUI::test_accessibility_features", "type": "Function", "lineno": 162}, {"nodeid": "tests/e2e/test_basic_ui.py::TestBasicUI::test_error_handling", "type": "Function", "lineno": 184}]}, {"nodeid": "tests/e2e/test_basic_ui.py", "outcome": "passed", "result": [{"nodeid": "tests/e2e/test_basic_ui.py::TestBasicUI", "type": "Class"}]}, {"nodeid": "tests/e2e/test_console_error_monitor.py::TestConsoleErrorMonitor", "outcome": "passed", "result": [{"nodeid": "tests/e2e/test_console_error_monitor.py::TestConsoleErrorMonitor::test_console_error_monitoring", "type": "Function", "lineno": 347}, {"nodeid": "tests/e2e/test_console_error_monitor.py::TestConsoleErrorMonitor::test_continuous_monitoring", "type": "Function", "lineno": 469}]}, {"nodeid": "tests/e2e/test_console_error_monitor.py", "outcome": "passed", "result": [{"nodeid": "tests/e2e/test_console_error_monitor.py::TestConsoleErrorMonitor", "type": "Class"}]}, {"nodeid": "tests/e2e/__init__.py", "outcome": "passed", "result": [{"nodeid": "tests/e2e/test_basic_ui.py", "type": "Module"}, {"nodeid": "tests/e2e/test_console_error_monitor.py", "type": "Module"}]}, {"nodeid": "tests/e2e/pages/__init__.py", "outcome": "passed", "result": []}, {"nodeid": "tests/e2e/scenarios/test_incident_workflow.py::TestIncidentWorkflowE2E", "outcome": "passed", "result": [{"nodeid": "tests/e2e/scenarios/test_incident_workflow.py::TestIncidentWorkflowE2E::test_create_incident_complete_workflow", "type": "Function", "lineno": 14}, {"nodeid": "tests/e2e/scenarios/test_incident_workflow.py::TestIncidentWorkflowE2E::test_incident_assignment_workflow", "type": "Function", "lineno": 50}, {"nodeid": "tests/e2e/scenarios/test_incident_workflow.py::TestIncidentWorkflowE2E::test_incident_status_transitions", "type": "Function", "lineno": 71}, {"nodeid": "tests/e2e/scenarios/test_incident_workflow.py::TestIncidentWorkflowE2E::test_incident_escalation_workflow", "type": "Function", "lineno": 110}, {"nodeid": "tests/e2e/scenarios/test_incident_workflow.py::TestIncidentWorkflowE2E::test_incident_history_tracking", "type": "Function", "lineno": 131}, {"nodeid": "tests/e2e/scenarios/test_incident_workflow.py::TestIncidentWorkflowE2E::test_incident_search_and_filter", "type": "Function", "lineno": 158}, {"nodeid": "tests/e2e/scenarios/test_incident_workflow.py::TestIncidentWorkflowE2E::test_incident_form_validation", "type": "Function", "lineno": 199}, {"nodeid": "tests/e2e/scenarios/test_incident_workflow.py::TestIncidentWorkflowE2E::test_incident_bulk_operations", "type": "Function", "lineno": 213}, {"nodeid": "tests/e2e/scenarios/test_incident_workflow.py::TestIncidentWorkflowE2E::test_incident_pagination", "type": "Function", "lineno": 235}, {"nodeid": "tests/e2e/scenarios/test_incident_workflow.py::TestIncidentWorkflowE2E::test_incident_edit_workflow", "type": "Function", "lineno": 263}]}, {"nodeid": "tests/e2e/scenarios/test_incident_workflow.py", "outcome": "passed", "result": [{"nodeid": "tests/e2e/scenarios/test_incident_workflow.py::TestIncidentWorkflowE2E", "type": "Class"}]}, {"nodeid": "tests/load/test_api_load.py::TestAPILoadPerformance", "outcome": "passed", "result": [{"nodeid": "tests/load/test_api_load.py::TestAPILoadPerformance::test_incident_list_performance", "type": "Function", "lineno": 53}, {"nodeid": "tests/load/test_api_load.py::TestAPILoadPerformance::test_incident_detail_performance", "type": "Function", "lineno": 80}, {"nodeid": "tests/load/test_api_load.py::TestAPILoadPerformance::test_incident_creation_performance", "type": "Function", "lineno": 113}, {"nodeid": "tests/load/test_api_load.py::TestAPILoadPerformance::test_incident_update_performance", "type": "Function", "lineno": 141}, {"nodeid": "tests/load/test_api_load.py::TestAPILoadPerformance::test_concurrent_incident_creation", "type": "Function", "lineno": 173}, {"nodeid": "tests/load/test_api_load.py::TestAPILoadPerformance::test_read_heavy_load", "type": "Function", "lineno": 266}, {"nodeid": "tests/load/test_api_load.py::TestAPILoadPerformance::test_sustained_load", "type": "Function", "lineno": 336}, {"nodeid": "tests/load/test_api_load.py::TestAPILoadPerformance::test_memory_usage_during_load", "type": "Function", "lineno": 428}]}, {"nodeid": "tests/load/test_api_load.py", "outcome": "passed", "result": [{"nodeid": "tests/load/test_api_load.py::TestAPILoadPerformance", "type": "Class"}]}, {"nodeid": "tests/load/test_api_performance.py::TestAPIPerformance", "outcome": "passed", "result": [{"nodeid": "tests/load/test_api_performance.py::TestAPIPerformance::test_single_incident_creation_performance", "type": "Function", "lineno": 17}, {"nodeid": "tests/load/test_api_performance.py::TestAPIPerformance::test_incident_list_query_performance", "type": "Function", "lineno": 36}, {"nodeid": "tests/load/test_api_performance.py::TestAPIPerformance::test_concurrent_incident_creation", "type": "Function", "lineno": 59}, {"nodeid": "tests/load/test_api_performance.py::TestAPIPerformance::test_api_rate_limiting_behavior", "type": "Function", "lineno": 111}, {"nodeid": "tests/load/test_api_performance.py::TestAPIPerformance::test_large_dataset_pagination_performance", "type": "Function", "lineno": 177}, {"nodeid": "tests/load/test_api_performance.py::TestAPIPerformance::test_complex_query_performance", "type": "Function", "lineno": 217}, {"nodeid": "tests/load/test_api_performance.py::TestAPIPerformance::test_bulk_operations_performance", "type": "Function", "lineno": 250}, {"nodeid": "tests/load/test_api_performance.py::TestAPIPerformance::test_api_response_time_vs_payload_size[1]", "type": "Function", "lineno": 280}, {"nodeid": "tests/load/test_api_performance.py::TestAPIPerformance::test_api_response_time_vs_payload_size[10]", "type": "Function", "lineno": 280}, {"nodeid": "tests/load/test_api_performance.py::TestAPIPerformance::test_api_response_time_vs_payload_size[100]", "type": "Function", "lineno": 280}, {"nodeid": "tests/load/test_api_performance.py::TestAPIPerformance::test_api_response_time_vs_payload_size[1000]", "type": "Function", "lineno": 280}, {"nodeid": "tests/load/test_api_performance.py::TestAPIPerformance::test_memory_usage_under_load", "type": "Function", "lineno": 309}, {"nodeid": "tests/load/test_api_performance.py::TestAPIPerformance::test_api_timeout_handling", "type": "Function", "lineno": 341}]}, {"nodeid": "tests/load/test_api_performance.py", "outcome": "passed", "result": [{"nodeid": "tests/load/test_api_performance.py::TestAPIPerformance", "type": "Class"}]}, {"nodeid": "tests/load/test_comprehensive_load.py::TestComprehensiveLoad", "outcome": "passed", "result": [{"nodeid": "tests/load/test_comprehensive_load.py::TestComprehensiveLoad::test_spike_load_testing", "type": "Function", "lineno": 24}, {"nodeid": "tests/load/test_comprehensive_load.py::TestComprehensiveLoad::test_endurance_testing", "type": "Function", "lineno": 152}, {"nodeid": "tests/load/test_comprehensive_load.py::TestComprehensiveLoad::test_volume_testing", "type": "Function", "lineno": 265}, {"nodeid": "tests/load/test_comprehensive_load.py::TestComprehensiveLoad::test_scalability_testing", "type": "Function", "lineno": 323}, {"nodeid": "tests/load/test_comprehensive_load.py::TestComprehensiveLoad::test_resource_consumption_monitoring", "type": "Function", "lineno": 442}, {"nodeid": "tests/load/test_comprehensive_load.py::TestComprehensiveLoad::test_recovery_after_load", "type": "Function", "lineno": 535}]}, {"nodeid": "tests/load/test_comprehensive_load.py", "outcome": "passed", "result": [{"nodeid": "tests/load/test_comprehensive_load.py::TestComprehensiveLoad", "type": "Class"}]}, {"nodeid": "tests/load/test_simple_load.py::TestBasicLoad", "outcome": "passed", "result": [{"nodeid": "tests/load/test_simple_load.py::TestBasicLoad::test_api_concurrent_requests", "type": "Function", "lineno": 14}, {"nodeid": "tests/load/test_simple_load.py::TestBasicLoad::test_api_sustained_load", "type": "Function", "lineno": 42}, {"nodeid": "tests/load/test_simple_load.py::TestBasicLoad::test_database_connection_pool", "type": "Function", "lineno": 86}, {"nodeid": "tests/load/test_simple_load.py::TestBasicLoad::test_memory_usage_under_load", "type": "Function", "lineno": 115}, {"nodeid": "tests/load/test_simple_load.py::TestBasicLoad::test_response_time_under_load", "type": "Function", "lineno": 141}]}, {"nodeid": "tests/load/test_simple_load.py::TestPerformanceBenchmarks", "outcome": "passed", "result": [{"nodeid": "tests/load/test_simple_load.py::TestPerformanceBenchmarks::test_json_serialization_benchmark", "type": "Function", "lineno": 196}, {"nodeid": "tests/load/test_simple_load.py::TestPerformanceBenchmarks::test_data_processing_benchmark", "type": "Function", "lineno": 220}]}, {"nodeid": "tests/load/test_simple_load.py", "outcome": "passed", "result": [{"nodeid": "tests/load/test_simple_load.py::TestBasicLoad", "type": "Class"}, {"nodeid": "tests/load/test_simple_load.py::TestPerformanceBenchmarks", "type": "Class"}]}, {"nodeid": "tests/utils/test_health_check.py::TestHealthChecker", "outcome": "passed", "result": []}, {"nodeid": "tests/utils/test_health_check.py", "outcome": "passed", "result": [{"nodeid": "tests/utils/test_health_check.py::TestHealthChecker", "type": "Class"}]}, {"nodeid": "tests/utils/test_runner.py", "outcome": "passed", "result": []}, {"nodeid": "tests/utils/test_suite_final_repair_engine.py", "outcome": "failed", "result": [], "longrepr": "ImportError while importing test module '/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/utils/test_suite_final_repair_engine.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.12/importlib/__init__.py:90: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/utils/test_suite_final_repair_engine.py:25: in <module>\n    import aiohttp\nE   ModuleNotFoundError: No module named 'aiohttp'"}, {"nodeid": "tests/utils/test_suite_infinite_loop_repair_engine.py::TestSuiteInfiniteLoopRepairEngine", "outcome": "passed", "result": []}, {"nodeid": "tests/utils/test_suite_infinite_loop_repair_engine.py", "outcome": "passed", "result": [{"nodeid": "tests/utils/test_suite_infinite_loop_repair_engine.py::TestSuiteInfiniteLoopRepairEngine", "type": "Class"}]}], "tests": [], "warnings": [{"message": "Please use `import python_multipart` instead.", "category": "PendingDeprecationWarning", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/starlette/formparsers.py", "lineno": 10}, {"message": "Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'env'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/fields.py", "lineno": 1093}, {"message": "Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'env'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/fields.py", "lineno": 1093}, {"message": "Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'env'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/fields.py", "lineno": 1093}, {"message": "Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'env'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/fields.py", "lineno": 1093}, {"message": "Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'env'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/fields.py", "lineno": 1093}, {"message": "Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'env'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/fields.py", "lineno": 1093}, {"message": "Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'env'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/fields.py", "lineno": 1093}, {"message": "Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'env'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/fields.py", "lineno": 1093}, {"message": "Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'env'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/fields.py", "lineno": 1093}, {"message": "Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'env'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/fields.py", "lineno": 1093}, {"message": "Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'env'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/fields.py", "lineno": 1093}, {"message": "Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'env'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/fields.py", "lineno": 1093}, {"message": "Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'env'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/fields.py", "lineno": 1093}, {"message": "Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'env'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/fields.py", "lineno": 1093}, {"message": "Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'env'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/fields.py", "lineno": 1093}, {"message": "Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'env'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/fields.py", "lineno": 1093}, {"message": "Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'env'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/fields.py", "lineno": 1093}, {"message": "'crypt' is deprecated and slated for removal in Python 3.13", "category": "DeprecationWarning", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/passlib/utils/__init__.py", "lineno": 854}, {"message": "The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)", "category": "MovedIn20Warning", "when": "config", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/app/db/base.py", "lineno": 21}, {"message": "`min_items` is deprecated and will be removed, use `min_length` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/fields.py", "lineno": 1062}, {"message": "`max_items` is deprecated and will be removed, use `max_length` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/fields.py", "lineno": 1068}, {"message": "Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/_internal/_config.py", "lineno": 323}, {"message": "Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/_internal/_config.py", "lineno": 323}, {"message": "Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/_internal/_config.py", "lineno": 323}, {"message": "Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/_internal/_config.py", "lineno": 323}, {"message": "Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/_internal/_config.py", "lineno": 323}, {"message": "Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/_internal/_config.py", "lineno": 323}, {"message": "Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/_internal/_config.py", "lineno": 323}, {"message": "Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/_internal/_config.py", "lineno": 323}, {"message": "Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/_internal/_config.py", "lineno": 323}, {"message": "Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/_internal/_config.py", "lineno": 323}, {"message": "Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/_internal/_config.py", "lineno": 323}, {"message": "Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/_internal/_config.py", "lineno": 323}, {"message": "Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/_internal/_config.py", "lineno": 323}, {"message": "Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/_internal/_config.py", "lineno": 323}, {"message": "Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/_internal/_config.py", "lineno": 323}, {"message": "Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/_internal/_config.py", "lineno": 323}, {"message": "Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/_internal/_config.py", "lineno": 323}, {"message": "`min_items` is deprecated and will be removed, use `min_length` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/home/kensan/.local/lib/python3.12/site-packages/pydantic/fields.py", "lineno": 1062}, {"message": "Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/app/schemas/attachment.py", "lineno": 152}, {"message": "Unknown pytest.mark.performance - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/test_suite_final_repair.py", "lineno": 79}, {"message": "Unknown pytest.mark.e2e - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/test_suite_final_repair.py", "lineno": 196}, {"message": "Unknown pytest.mark.load - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/test_suite_final_repair.py", "lineno": 222}, {"message": "Unknown pytest.mark.security - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/test_suite_final_repair.py", "lineno": 259}, {"message": "Unknown pytest.mark.comprehensive - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/test_suite_final_repair.py", "lineno": 285}, {"message": "Unknown pytest.mark.realtime - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/test_suite_final_repair.py", "lineno": 329}, {"message": "Unknown pytest.mark.automation - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/test_suite_final_repair.py", "lineno": 368}, {"message": "Unknown pytest.mark.final_test_suite - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/test_suite_final_repair.py", "lineno": 401}, {"message": "Unknown pytest.mark.comprehensive - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/api/test_comprehensive_api.py", "lineno": 14}, {"message": "Unknown pytest.mark.problems - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/api/test_comprehensive_api.py", "lineno": 126}, {"message": "Unknown pytest.mark.changes - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/api/test_comprehensive_api.py", "lineno": 153}, {"message": "Unknown pytest.mark.cmdb - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/api/test_comprehensive_api.py", "lineno": 181}, {"message": "Unknown pytest.mark.reports - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/api/test_comprehensive_api.py", "lineno": 243}, {"message": "Unknown pytest.mark.notifications - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/api/test_comprehensive_api.py", "lineno": 288}, {"message": "Unknown pytest.mark.users - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/api/test_comprehensive_api.py", "lineno": 329}, {"message": "Unknown pytest.mark.categories - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/api/test_comprehensive_api.py", "lineno": 370}, {"message": "Unknown pytest.mark.teams - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/api/test_comprehensive_api.py", "lineno": 415}, {"message": "Unknown pytest.mark.health - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/api/test_comprehensive_api.py", "lineno": 455}, {"message": "Unknown pytest.mark.search - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/api/test_comprehensive_api.py", "lineno": 490}, {"message": "Unknown pytest.mark.performance - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/api/test_comprehensive_api.py", "lineno": 543}, {"message": "Unknown pytest.mark.load - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/api/test_comprehensive_api.py", "lineno": 659}, {"message": "Unknown pytest.mark.security - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/api/test_comprehensive_api.py", "lineno": 704}, {"message": "cannot collect test class 'TestReportGenerator' because it has a __init__ constructor (from: tests/automation/test_report_generator.py)", "category": "PytestCollectionWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/automation/test_report_generator.py", "lineno": 18}, {"message": "Unknown pytest.mark.e2e - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/e2e/test_basic_ui.py", "lineno": 8}, {"message": "Unknown pytest.mark.e2e - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/e2e/scenarios/test_incident_workflow.py", "lineno": 9}, {"message": "Unknown pytest.mark.load - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/load/test_api_load.py", "lineno": 14}, {"message": "Unknown pytest.mark.load - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/load/test_api_performance.py", "lineno": 13}, {"message": "Unknown pytest.mark.load - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/load/test_comprehensive_load.py", "lineno": 20}, {"message": "Unknown pytest.mark.load - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/load/test_simple_load.py", "lineno": 11}, {"message": "Unknown pytest.mark.load - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/load/test_simple_load.py", "lineno": 192}, {"message": "cannot collect test class 'TestHealthChecker' because it has a __init__ constructor (from: tests/utils/test_health_check.py)", "category": "PytestCollectionWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/utils/test_health_check.py", "lineno": 18}, {"message": "cannot collect test class 'TestSuiteInfiniteLoopRepairEngine' because it has a __init__ constructor (from: tests/utils/test_suite_infinite_loop_repair_engine.py)", "category": "PytestCollectionWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/tests/utils/test_suite_infinite_loop_repair_engine.py", "lineno": 29}]}